### ISSUE TITLE
clapack: []int32 for lapack_int*?

### ISSUE THREAD

**Issue by vladimir-ch** [gonum/lapack#161]
1. Why use `int32`, why not `int`?
2. In case of `iwork` or `ipiv` parameters, they are arrays of `int`. However, in `?trexc`, `ifst` and `ilst` are just single in/out integers, so using a slice for them seems inappropriate.

**Comment by kortschak** [comment]
1. Because the types in C/Fortran are `C.int`.

2. The clapack (were we going to change the name of this?) package should in no way be considered a Go API. The use of []int32 reflects the method of passing integers into/out of Fortran functions. We inherit this from LAPACKE. In the case of the cblas package we do a fair amount of work to conform the C/Fortran calls to a Go-like API. This has been progressively refined with a reasonable amount of pain and only because the BLAS API is small enough. Ensuring that we have all the correct mapping between types in lapacke.h and the Go shims would not be trivial given the very loose approach the authors of that file have taken with naming and the immense size of the API surface. The design of clapack is to be "just good enough" for us to in lapack64 etc.

**Comment by vladimir-ch** [comment]
> Because the types in C/Fortran are C.int.

And I guess that's always 4 bytes? (I'm so grateful for Go)

> The clapack (were we going to change the name of this?)

I think `lapacke` is a more accurate name but I'm not sure if it hasn't been considered before.

Thanks for the clarification.

**Comment by kortschak** [comment]
>I think `lapacke` is a more accurate name but I'm not sure if it hasn't been considered before.

I'm pretty sure you suggested it before, and I have no objections to this. It's not an API difficulty, because we don't plan to explicitly support it. It's just a matter of timing. If you want to send the PR for that, it's fine with me.
